fast repo downloader
Hexlet/hexlet-exercise-kit pull request #38
Opened 2022-10-18 21:51 UTC by fey

Легендарный рубишный загрузчик от Стаса.
С небольшими доработками - конфиг линтера, поправил загрузку списка проектов (убрал ручную пагинацию), добавил прогрессбар. Обработки ошибок пока нет.

2022-10-19 13:37 UTC, corsicanec82 reviewed
Ну а в целом кажется что всё основное хорошо

2022-10-19 13:37 UTC, corsicanec82 commented on Makefile
> +DOWNLOADER_IMAGE_NAME=hexlet/gitlab-downloader
в принципе тут нет проблемы, но специально делал другое название образа  и директории доунлоадера чтобы не конфликтовало с образом пайтон

2022-10-19 13:37 UTC, corsicanec82 commented on Makefile
> +	docker run --rm -it \
давай вынесем команду docker run в отдельную команду make (например downloader-run), в которую будем просто передавать нужную команду запуска. Например
```
downloader-bash:
  make downloader-run C=bash

downloader-lint:
  make downloader-run C="make lint"

...
```
Так здорово уменьшится дублирование

2022-10-19 13:37 UTC, corsicanec82 commented on README.md
> +PARALLEL=4
для нашего гитлаба спокойно можно юзать 8, я на этом значении проверял - полёт нормальный. Это на общем гитлабе выстреливало ограничение по запросам на апи.
Даже в случае чего мы ограничением по апи сами управляем и его можно будет поднять выше, чтобы скачивалось быстрее

2022-10-19 13:37 UTC, corsicanec82 commented on README.md
> +make clone SSH_KEYS_PATH=/specific/path/to/your/.ssh
Не вижу чтобы в командах использовалась переменная SSH_KEYS_PATH, сейчас путь к ключам там захардкожен v $(HOME)/.ssh

2022-10-19 13:37 UTC, corsicanec82 commented on repo-downloader/.env.template
> +PARALLEL=4
давай дефолт 8 как в основном темплейте

2022-10-19 13:37 UTC, corsicanec82 commented on repo-downloader/.env.example.full
> +# optional
думаю что стоит оставить один темплейт - этот полный, они отличаются только наличием GITLAB_API_ENDPOINT. Тогда из dockerfile можно будет выкинуть установку GITLAB_API_ENDPOINT=...

2022-10-19 13:37 UTC, corsicanec82 commented on repo-downloader/lib/repo_downloader/downloader.rb
> +    DEFAULT_PARALLELS = 4
лучше 8, будет быстрее

2022-10-19 18:32 UTC, fey commented on repo-downloader/.env.example.full
> +# optional
fixed

2022-10-19 18:32 UTC, fey commented on repo-downloader/lib/repo_downloader/downloader.rb
> +    DEFAULT_PARALLELS = 4
fixed

2022-10-19 18:33 UTC, fey commented on repo-downloader/.env.template
> +PARALLEL=4
заменил на full

2022-10-19 18:33 UTC, fey commented on README.md
> +make clone SSH_KEYS_PATH=/specific/path/to/your/.ssh
Поправил мейкфайл

2022-10-19 18:34 UTC, fey commented on README.md
> +PARALLEL=4
поменял на 8, просто по с большим количеством параллельных потоков падала загрузка, типа адрес не найден, с низкими значениями работало постабильней

2022-10-19 18:34 UTC, fey commented on Makefile
> +	docker run --rm -it \
fixed

2022-10-19 19:19 UTC, fey commented on Makefile
> +	docker run --rm -it \
Для команды линтера убрал переиспользование команды, потому что в github actions не должно быть `-it` флага при запуске контейнера в CI
Плюс для линтера не нужны переменные окружения и волюм с репозиториями

2022-10-20 10:31 UTC, corsicanec82 requested changes
Дело близится к финишу.
Я уже заготовил обработку ошибок и немного упростил код. Так что жду доработок после чего закину решение.
P.S. кстати насчет parallel 8. Специально сегодня проверил на значении 12 и ошибок также нет. Ты писал что возникала ошибка с получением репы. Это было ещё на старом gitlab.com или уже на новом?

2022-10-20 10:31 UTC, corsicanec82 commented on README.md
> +PARALLEL=8
GITLAB_API_ENDPOINT и PARALLEL опциональные. кажется что тут их описывать не стоит, потому как складывается впечатление что они обязательные

2022-10-20 10:31 UTC, corsicanec82 commented on repo-downloader/.env.template
> +PATH_TO_REPOS=
при таком раскладе в коде значение этой переменной будет равно пустой строке и репы начнут скачиваться в директорию repo-downloader

2022-10-20 10:31 UTC, corsicanec82 commented on repo-downloader/.env.template
> +PATH_TO_REPOS=
давай вообще выпилим использование этой переменной. kit у нас заточен на определённую файловую структуру, потому нет смысла скачивать в какое то другое место.

2022-10-20 10:31 UTC, corsicanec82 commented on repo-downloader/.env.template
> +PARALLEL=
с этой переменной аналогичная история. Распечатай в консоль при запуске значение parallels в коде, оно будет равно 0.

2022-10-20 10:31 UTC, corsicanec82 commented on repo-downloader/Dockerfile
> +ENV PATH_TO_REPOS=/home/tirion/repos
Эту переменную можно установить выше и переиспользовать её значение в RUN mkdir /home/tirion/repos

2022-10-20 10:31 UTC, corsicanec82 commented on repo-downloader/lib/repo_downloader/downloader.rb
> +      @parallel = options.fetch(:parallel, DEFAULT_PARALLELS).to_i
кажется хорошей идеей будет перенести формирование значений в один модуль, например в cli.rb
Сейчас формирование расползлось по четырём местам. В cli, в downloader.rb, .env файл и Makefile (это я про фильтр).
Предлагаю заполнить все значения которые можно дефолтными в .env файле. В makefile при необходимости будет происходить переопределение, как в случае filter. А в cli нормализация всех значений и создание инстанса класса downloader с уже подготовленными значениями.

2022-10-20 10:31 UTC, corsicanec82 commented on Makefile
> +	docker run --rm \
без интерактивного режима не получится остановить процесс с помощью Ctrl+C

2022-10-20 10:31 UTC, corsicanec82 commented on Makefile
> +	make downloader-run C=bash
эта команда также выполняется без интерактивного режима и не имеет смысла

2022-10-20 20:35 UTC, fey commented on Makefile
> +	docker run --rm \
Поправил

2022-10-20 20:35 UTC, fey commented on Makefile
> +	make downloader-run C=bash
Поправил

2022-10-20 20:35 UTC, fey commented on repo-downloader/.env.template
> +PATH_TO_REPOS=
Убрал

2022-10-20 20:35 UTC, fey commented on README.md
> +PARALLEL=8
Поправил

2022-10-20 21:11 UTC, fey commented
Добавил гем для управленя курсором, но не сломал переписывание текущего проекта. Но хотя  бы отображается процесс и что в целом происходит.

2022-10-20 21:12 UTC, fey commented on repo-downloader/.env.template
> +PARALLEL=
Поправил

2022-10-20 21:12 UTC, fey commented on repo-downloader/Dockerfile
> +ENV PATH_TO_REPOS=/home/tirion/repos
Поправил

2022-10-20 21:16 UTC, fey commented on repo-downloader/.env.template
> +PATH_TO_REPOS=
Из енва убрал, но с использованием будет сложнее.
Ведь щас образ билдится в контексте репо загрузчика. А чтобы отобразить изменения на хосте, нужно будет пробросить волюмы, либо билдить образ по другому.
Короче надо в любом случае уметь складывать все скачанное куда-то сбоку

2022-10-21 06:53 UTC, corsicanec82 commented on repo-downloader/.env.template
> +PATH_TO_REPOS=
Ну я имел в виду выпилить управление путём со стороны. Так то да понятно что нужно складывать в другое место

2022-10-21 06:54 UTC, merged